# Dockerfile.python
# Use an official Python runtime as a parent image
FROM  python:3.10-slim

# Set working directory
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    libpq-dev build-essential curl jq procps && \
    rm -rf /var/lib/apt/lists/*

# Upgrade pip
RUN python -m pip install --upgrade pip

# Copy requirements file and install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of your application code
COPY app/. .

# Make sure run.sh script is executable
RUN chmod +x ./run.sh

# Default command to run your Python application
CMD ["./run.sh"]
