version: '3.8'
services:
  ravagent-ollama:
    image: ollama/ollama:latest  # Use the latest Ollama image
    ports:
      - "11434:11434"  # Map port 11434 on the host to port 11434 in the container
    environment:
      - OLLAMA_HOST=http://ravagent-ollama:11434  # Set host variable for accessibility
    volumes:
      - ollama_data:/root/.ollama  # Persist data in the Ollama container
    networks:
      - ravagent_network  # Use a custom network for internal communication
    env_file:
      - .env  # Load environment variables from .env file

  langflow:
    build:
      context: .
      dockerfile: Dockerfile.langflow  # Ensure this points to your Langflow Dockerfile
    ports:
      - "7860:7860"  # Map port 7860 to host
    depends_on:
      - ravagent-ollama
    networks:
      - ravagent_network  # Use the same network for internal communication
    env_file:
      - .env  # Load environment variables from .env file

volumes:
  ollama_data:  # Define the volume to persist data

networks:
  ravagent_network:
    driver: bridge  # Define a custom network using bridge driver
