version: '3.8'
services:
  ravagent-ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_HOST=http://ravagent-ollama:11434
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - ravagent_network
    env_file:
      - .env

  langflow:
    build:
      context: .
      dockerfile: Dockerfile.langflow  # Ensure this points to your Langflow Dockerfile
    ports:
      - "7860:7860"
    depends_on:
      - ravagent-ollama
    networks:
      - ravagent_network
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Ensure this line is present

volumes:
  ollama_data:

networks:
  ravagent_network:
    driver: bridge
